language: java
sudo: false
script: mvn clean verify
after_success:
  - mvn cobertura:cobertura
  - mvn coveralls:report -DrepoToken="1Mxkyn1KKuq2VLGMnNjIi7eC6UQVPHrOz"
  - bash <(curl -s https://codecov.io/bash) -t c35c0b76-d85c-4e4d-8429-3b0146725318
